spring:
  application:
    name: PartnershipCompensationSystemMS

  datasource:
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        url: ${MYSQL_URL}
#    username: "root"
#    password: "root"
#    url: "jdbc:mysql://localhost:3306/user_db?useSSL=false&allowMultiQueries=true&serverTimezone=UTC&createDatabaseIfNotExist=true"

  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8081